=== uktrade/market-access-frontend/src/data/schema/backend/barriers/assessment.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Detail of an assessment",

	"type": "object",
	"required": [
		"id",
		"impact",
		"explantion",
		"value_to_economy",
		"import_market_size",
		"commercial_value",
		"export_value",
		"documents",
		"created_on",
		"created_by"
	],
	"properties": {

		"id": { "$ref": "$refs/common.json#/small-int" },
		"impact": {
			"type": "string",
			"enum": [ "ONE", "TWO", "THREE", "FOUR" ]
		},
		"explantion": { "$ref": "$refs/common.json#/words" },
		"value_to_economy": { "$ref": "$refs/common.json#/int" },
		"import_market_size": { "$ref": "$refs/common.json#/int" },
		"commercial_value": { "$ref": "$refs/common.json#/int" },
		"export_value": { "$ref": "$refs/common.json#/int" },
		"documents": {
			"type": "array",
			"minItems": 0,
			"maxItems": 5,
			"items": { "$ref": "$refs/common.json#/document" }
		},
		"created_on": { "$ref": "$refs/common.json#/past-date" },
		"created_by": { "$ref": "$refs/common.json#/user" }
	}
}

=== uktrade/market-access-frontend/src/test/app/fake-data/backend/barriers/assessment.json
{
   "id": 3,
   "impact": "THREE",
   "explantion": "occaecati itaque quo",
   "value_to_economy": 55197,
   "import_market_size": 16816,
   "commercial_value": 51888,
   "export_value": 50309,
   "documents": [
		{
         "id": "4a922639-514e-4389-8967-1fde85acaf6c",
         "name": "consequatur",
         "size": 13,
         "status": "virus_scanned"
      },
      {
         "id": "a3edf3fc-2933-4773-9a26-4571acdfa391",
         "name": "eos",
         "size": 11,
         "status": "virus_scanned"
      }
	],
   "created_on": "Mon Jan 21 2019 09:09:38 GMT+0000 (Greenwich Mean Time)",
   "created_by": {
      "id": 19,
      "name": "voluptas"
   }
}
