=== uktrade/market-access-frontend/src/data/schema/backend/barriers/barrier.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Detail of a report",

	"type": "object",
	"required": [
		"id",
		"barrier_type",
		"barrier_title",
		"summary",
		"report",
		"current_status",
		"reported_on",
		"company",
		"export_country",
		"has_legal_infringement",
		"wto_infringement",
		"fta_infringement",
		"other_infringement",
		"infringement_summary"
	],
	"properties": {

		"id": { "$ref": "$refs/common.json#/uuid" },

		"barrier_type": {
			"type": "object",
			"required": [
				"id",
				"title"
			],
			"properties": {

				"id": { "$ref": "$refs/common.json#/small-int" },
				"title": { "$ref": "$refs/common.json#/words" }
			}
		},

		"barrier_title": {
			"type": "string",
			"faker": "lorem.words"
		},

		"summary": { "$ref": "$refs/common.json#/paragraph" },

		"report": {
			"type": "object",
			"required": [
				"id",
				"problem_status",
				"company"
			],
			"properties": {

				"id": { "$ref": "$refs/common.json#/small-int" },

				"problem_status": {
					"type": "number",
					"enum": [ 1, 2, 3 ]
				},

				"company": {
					"$ref": "#/refs/company"
				}
			}
		},

		"current_status": {
			"type": "object",
			"required": [ "status" ],
			"properties": {
				"status": {
					"type": "number",
					"enum": [ 1, 2, 3, 4 ]
				}
			}
		},

		"reported_on": { "$ref": "$refs/common.json#/past-date" },
		"company": { "$ref": "#/refs/company" },
		"export_country": { "$ref": "$refs/common.json#/uuid" },

		"has_legal_infringement": {
			"type": "string",
			"enum": [ "1", "2", "3" ]
		},

		"wto_infringement": { "$ref": "$refs/common.json#/boolean" },
		"fta_infringement": { "$ref": "$refs/common.json#/boolean" },
		"other_infringement": { "$ref": "$refs/common.json#/boolean" },
		"infringement_summary":  { "$ref": "$refs/common.json#/paragraph" }
	},

	"refs": {
		"company": {
			"type": "object",
			"required": [
				"id",
				"name",
				"sector_id",
				"sector_name"
			],
			"properties": {

				"id": { "$ref": "$refs/common.json#/uuid" },
				"name": { "$ref": "$refs/common.json#/words" },
				"sector_id": { "$ref": "$refs/common.json#/uuid" },
				"sector_name": { "$ref": "$refs/common.json#/words" }
			}
		}
	}
}

=== uktrade/market-access-frontend/src/test/app/fake-data/backend/barriers/barrier.json
{
   "id": "c6c39e5e-5bb4-422a-8936-f8dabab9bbff",
   "barrier_type": {
      "id": 17,
      "title": "officia assumenda maiores"
   },
   "barrier_title": "fugiat esse qui",
   "summary": "Iste aut nisi quisquam aut non est architecto unde soluta. Molestias omnis eos. Sit aut rerum sit impedit ut ut recusandae et.",
   "report": {
      "id": 8,
      "problem_status": 2,
      "company": {
         "id": "884f6930-fac1-4feb-9233-ae5b1e219146",
         "name": "velit voluptatibus ea",
         "sector_id": "e38eb400-5df1-4bc2-a81f-0d89a25c534b",
         "sector_name": "quo accusamus qui"
      }
   },
   "current_status": {
      "status": 3
   },
   "reported_on": "Fri Jun 22 2018 13:21:43 GMT+0100 (BST)",
   "company": {
      "id": "4397afb6-6725-445f-bfe9-e87683677ca9",
      "name": "ipsa commodi unde",
      "sector_id": "72d54511-61b2-482c-ab65-b937386ea6f5",
      "sector_name": "id aut et"
   },
   "export_country": "0f4156b9-ae0f-42f4-9af2-257a8f948c63",
   "has_legal_infringement": "3",
   "wto_infringement": false,
   "fta_infringement": true,
   "other_infringement": false,
   "infringement_summary": "Aut aliquid omnis qui omnis ipsam eum et veritatis fuga. Odio temporibus reiciendis suscipit non voluptatem suscipit. Provident adipisci corrupti aspernatur voluptas recusandae."
}
